version: 2.1

orbs:
  node: circleci/node@4.7.0
  win: circleci/windows@2.2.0

executors:
  linux-executor:
    docker:
      - image: cimg/node:14.18.0
  macos-executor:
    macos:
      xcode: 12.5.1

workflows:
  build-test-deploy:
    jobs:
      - test
      - package-linux:
          filters: &package-filters
            branches:
              only:
                - /^build\/.*/
          requires:
            - test
      - package-windows:
          filters:
            <<: *package-filters
          requires:
            - test
      - package-mac:
          filters:
            <<: *package-filters
          requires:
            - test
      - deploy-artifacts:
          requires:
            - package-linux
            - package-windows
            - package-mac

jobs:
  test:
    executor: linux-executor
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npx lerna bootstrap
      - run: npx lerna run lint:js
      - run: npx lerna run lint:styles
      - run: npx lerna run build
      - run: npx lerna run test --stream

  package-linux:
    executor: linux-executor
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npx lerna bootstrap
      - run: npx lerna run build
      - run: npx lerna run package:linux --stream
      - persist_to_workspace:
          root: packages/desktop/dist/packages
          paths:
            - amethyst-writer-*

  package-windows:
    executor: win/default
    steps:
      - checkout
      - run: npx lerna bootstrap
      - run: npx lerna run build
      - run: npx lerna run package:windows --stream
      - persist_to_workspace:
          root: packages/desktop/dist/packages
          paths:
            - amethyst-writer-*

  package-mac:
    executor: macos-executor
    steps:
      - checkout
      - run: npx lerna bootstrap
      - run: npx lerna run build
      - run: npx lerna run package:macos --stream
      - persist_to_workspace:
          root: packages/desktop/dist/packages
          paths:
            - amethyst-writer-*

  deploy-artifacts:
    executor: linux-executor
    steps:
      - checkout
      - attach_workspace:
          at: packages/desktop/dist/packages
      - node/install-packages:
          pkg-manager: npm
      - run: npx lerna bootstrap
      - run: npx lerna run deploy-artifacts --scope=@amethyst-writer/desktop --stream
