version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    docker:
      - image: cimg/node:14.10.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npx lerna bootstrap
      - run: npx lerna run build
